import About from '@/components/About'
import Main from '@/components/Main'
import Head from 'next/head'




export default function Home() {
  return (
    <div>
      <Head>
        <title>Charles | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favinv.jpg" />
      </Head>
      <Main />
      <About />
    </div>

  )
}
